//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.EthereumExample"/> </summary
    public sealed class EthereumExampleClient : MicroserviceClient
    {
        
        public EthereumExampleClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        /// <summary>
        /// Call the AssociateWallet method on the EthereumExample microservice
        /// <see cref="Beamable.Microservices.EthereumExample.AssociateWallet"/>
        /// </summary>
        public Beamable.Common.Promise<string> AssociateWallet(string msg1, string signature1)
        {
            string serialized_msg1 = this.SerializeArgument<string>(msg1);
            string serialized_signature1 = this.SerializeArgument<string>(signature1);
            string[] serializedFields = new string[] {
                    serialized_msg1,
                    serialized_signature1};
            return this.Request<string>("EthereumExample", "AssociateWallet", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersEthereumExampleClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForEthereumExampleClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<EthereumExampleClient>();
        }
        
        public static EthereumExampleClient EthereumExample(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<EthereumExampleClient>();
        }
    }
}
